### ISSUE TITLE
An Android app that builds on version 0.22.1 shows a blank screen and doesn't work

### ISSUE THREAD

**Issue by NHLOCAL** [flet-dev/flet#3479]
### Duplicate Check

- [ ] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

When I tried to build an APK application with the build command, the application showed a black screen every time. Even when I tried to use the example application (using flet create), the application showed a black screen and did not work at all, not even after waiting for several minutes.
When I went back to version 0.22.0 the application worked smoothly and properly

### To reproduce

Irrelevant

### Operating System

Windows

### Operating system details

windows 11 26120.751

### Flet version

0.22.1

### Regression

Yes, it used to work in a previous Flet version (please specify the version in additional details)

### Additional details

Version 0.22.0 works great for this operation

Besides that, I noticed that the updated version doubled the size of the application from 40 MB to about 80 MB

**Comment by Muddassirofficial** [comment]
> ### Duplicate Check
> 
> - [ ] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates
> 
> ### Describe the bug
> 
> When I tried to build an APK application with the build command, the application showed a black screen every time. Even when I tried to use the example application (using flet create), the application showed a black screen and did not work at all, not even after waiting for several minutes.
> When I went back to version 0.22.0 the application worked smoothly and properly
> 
> ### Code
> 
> _No response_
> 
> ### To reproduce
> 
> Irrelevant
> 
> ### Expected behavior
> 
> _No response_
> 
> ### Screenshots
> 
> _No response_
> 
> ### Operating System
> 
> Windows
> 
> ### Operating system details
> 
> windows 11 26120.751
> 
> ### Flet version
> 
> 0.22.1
> 
> ### Regression
> 
> Yes, it used to work in a previous Flet version (please specify the version in additional details)
> 
> ### Suggestions
> 
> _No response_
> 
> ### Additional details
> 
> Version 0.22.0 works great for this operation
> 
> Besides that, I noticed that the updated version doubled the size of the application from 40 MB to about 80 MB

Also facing same issue

**Comment by ixenion** [comment]
Check #3465 - there is answer.
In short: use older version of flet)
0.22.0 for example

**Comment by NHLOCAL** [comment]
Has the problem been fixed in version 0.23?

**Comment by Muddassirofficial** [comment]
> Has the problem been fixed in version 0.23?

still not fixed in  0.23 and  0.23.1

**Comment by Lucasapn2** [comment]
I am also facing the same problem, white screen after opening the apk, has anyone been able to solve it?

**Comment by Muddassirofficial** [comment]
> I am also facing the same problem, white screen after opening the apk, has anyone been able to solve it?

it is not solved even if we build apk with older version 0.22.0 now datatables disappears from our mobile application after building apk

**Comment by Lucasapn2** [comment]
I am facing an error when opening the apk it appears on a white screen, how can I resolve it? Is there any stable version? where it actually works?

**Comment by Muddassirofficial** [comment]
> I am facing an error when opening the apk it appears on a white screen, how can I resolve it? Is there any stable version? where it actually works?

Only works in 0.22.0

**Comment by ndonkoHenri** [comment]
Closing in favor of #3511
