### ISSUE TITLE
White Screen After Launching Apk flet 0.23.1

### ISSUE THREAD

**Issue by Muddassirofficial** [flet-dev/flet#3511]
### Duplicate Check

- [X] I have searched the [opened issues](https://github.com/flet-dev/flet/issues) and there are no duplicates

### Describe the bug

last day new update come (flet 0.23.1) but it has same issue like previous version its building apk of double size and when we run it on mobile device its showing blank screen as only older version (flet 0.22.0) is working fine and stable kindly its request from community to resolve this issue as soon as possible because our whole project is stucked we even cant deployed because many widgets depends on new release

### To reproduce

![image](https://github.com/flet-dev/flet/assets/135708579/a27ba264-7dab-4eac-b14b-8406a61ae1f8)

### Operating System

Windows

### Operating system details

Android

### Flet version

0.23.1

### Regression

No, it isn't

**Comment by Muddassirofficial** [comment]
Any update about this issue

**Comment by nastiliano** [comment]
Hello,

3 days ago I upgraded to "Flet v.0.23" and I upgraded "Flutter" to last version and for me (in Linux) it was a complete disaster.

Tonight I'm going to try v0.23.1 in Linux. (code and build) 

In windows I can code normally with v.0.23.1 (I didn't try to build yet....)

Best regards.

**Comment by nastiliano** [comment]
Hello.

I confirm in Linux (Ubuntu 24.04 - Linux 6.8.0-35-generic - Gnome 46 ) is possible code but not possible to build.

Thanks.

**Comment by nastiliano** [comment]
Hello.

I can confirm in MacOS (14.5 - Intel Processor) I can't even "compile" code with Visual Studio.
Black screen appears.

Thanks, best regards

**Comment by FeodorFitsner** [comment]
It should be fixed now in 0.23.1.

Please cleanup Cookiecutter cache before running `flet build` command.

On Windows:

```
rd /s /q %USERPROFILE%\.cookiecutters
```

On Mac/Linux:

```
rm -rf ~/.cookiecutters
```

**Comment by NHLOCAL** [comment]
Now tested on Windows and working for Campol to apk!
The size is also correct and is in the 40 MB area as in the old versions

**Comment by nastiliano** [comment]
Tested in Linux. Ok again!

Thank you very much.

**Comment by Laztef** [comment]
In 0.23.2 build apk is working, but the apk size with the counter example is about 140 MB, in the mobile device the final size is 188MB and this generate CACHE and DATA (224 MB). 
 The first run display a whitescreen, but if i wait a few moment (1/2 minutes) the app run (i understand that app generate the DATA and CACHE).
 How can i accelerate this process?. Or,  how can i jump this process of whitescreen??

**Comment by sorincirneala** [comment]
I am still having the white screen, it seems it's only fixed on some systems.
I am on Window 11, Flet 0.23.2 and I already tried deleting the Cookiecutter cache

**Comment by nastiliano** [comment]
And on MacOS Sonoma black screen too.

Try to install the last beta version:

pip install flet==0.24.0.dev3274


It "works" (more or less) on MacOS Sonoma.

Thanks

**Comment by ndonkoHenri** [comment]
What Flutter versions are you using to package?
Could you guys also share the output of `flutter doctor`?

**Comment by Laztef** [comment]
I can build and run the flet app.
FLET VERSION : 0.23.1
FLUTTER VERSION: Flutter 3.24.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 80c2e84975 (3 weeks ago) • 2024-07-30 23:06:49 +0700
Engine • revision b8800d88be
Tools • Dart 3.5.0 • DevTools 2.37.2.
But the first run of the app on Android (phone) it takes a long time to appear the main page. Can be it solved?

**Comment by sorincodes** [comment]
Here is the flutter doctor summary
[√] Flutter (Channel stable, 3.24.1, on Microsoft Windows [Version 10.0.22631.4037], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2024.1)
[√] IntelliJ IDEA Community Edition (version 2023.2)
[√] VS Code (version 1.92.1)
[√] Connected device (4 available)
[√] Network resources

PYTHON: 3.11.3
FLET: 0.23.2
Flutter 3.24.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5874a72aa4 (2 days ago) • 2024-08-20 16:46:00 -0500
Engine • revision c9b9d5780d
Tools • Dart 3.5.1 • DevTools 2.37.2

**Comment by ndonkoHenri** [comment]
@Laztef please share the output of `flutter doctor`.
@sorincodes please share the full build logs in `--verbose` mode.

**Comment by sorincodes** [comment]
Here are my build logs: https://gist.github.com/sorincodes/5618798d7d3e09f7ae0f416870bc310a
